name: TER
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - statsmodels
  - pyarrow
  - matplotlib
  - seaborn
  - thefuzz
  - mystmd
  - ipykernel
  - r-irkernel # R kernel for 00 - Data extraction.ipynb