name: TER
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - pyarrow
  - matplotlib
  - seaborn
  - scikit-learn
  - ipywidgets
  - ipykernel
  - thefuzz
  - jupyterlab>=4.0.0
  - jupyterlab-myst>=2.0.0
  - myst-nb
  - r-irkernel # R kernel for 02 - Data extraction.ipynb